### ISSUE TITLE
Deprecation warnings in Ruby 2.7

### ISSUE THREAD

**Issue by nuxy** [deivid-rodriguez/pry-byebug#358]
I don't think this warrants much explaination.  This should be fixed.

```
/usr/local/bundle/ruby/2.7.0/gems/pry-byebug-3.8.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
```

**Comment by Adre** [comment]
Looks like this is a pry-byebug 3.8 rather than being Ruby 2.7 specific.

There was a [change in the pry interface a couple of years ago](https://github.com/pry/pry/commit/e6ac84e99c0e32dc2641f85945594feeaf68051b) which changed the params for this, causing the deprecation you're seeing.

I ran into this deprecation when doing a `bundle update` which updated to the latest version of `pry` (0.14.1), causing `pry-byebug` to get _downgraded_ from 3.9.0 to 3.8.0 due to its dependencies.

- 3.9.0 requires `pry ~> 0.13.0`
- 3.8.0 requires `pry ~> 0.10`

Apologies if this is a separate issue to what you're raising. I just wondered, given the timing of the issue and the release of `pry 0.14`, whether you're in the same boat! I welcome your thoughts.

**Comment by nuxy** [comment]
@Adre - Most definitely related.  I was able to resolve this warning by updating my `Gemfile` to force the version:

```
gem "pry-byebug", "3.9.0"
```

Closing this issue.
